try{
    let a=6;
    console.log('sum=',a+b);
    
}
catch(err){
console.log('error=',err.message);

}
finally{
    console.log('execution completed.');
    
}